# Generated by Django 5.2 on 2025-04-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_airport', models.CharField(max_length=3, verbose_name='Departure airport')),
                ('arrival_airport', models.CharField(max_length=3, verbose_name='Arrival airport')),
                ('departure_time', models.DateTimeField(verbose_name='Departure time')),
                ('arrival_time', models.DateTimeField(verbose_name='Arrival time')),
                ('stops', models.IntegerField(verbose_name='Stops')),
                ('airline_name', models.CharField(max_length=50, verbose_name='Airline name')),
                ('airline_id', models.CharField(max_length=2, verbose_name='Airline ID')),
                ('duration_mins', models.IntegerField(verbose_name='Duration mins')),
            ],
        ),
        migrations.CreateModel(
            name='Itineraries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Price')),
                ('agent', models.CharField(max_length=50, verbose_name='Agent')),
                ('agent_rating', models.FloatField(verbose_name='Agent rating')),
                ('legs', models.ManyToManyField(to='flights.leg', verbose_name='Legs')),
            ],
        ),
    ]
