# Generated by Django 5.2 on 2025-04-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraries',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
