# Generated by Django 5.2 on 2025-04-22 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_itineraries_id_alter_leg_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Itineraries',
            new_name='Itinerarie',
        ),
    ]
